[phases.setup]
nixPkgs = ["...", "chromium", "xvfb-run"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "playwright install chromium",
    "playwright install-deps chromium"
]

[start]
cmd = "python api_server.py"

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/app/browsers"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "0"
